schema_version = 1

project {
  license          = "MIT"
  copyright_holder = "Proact"
  copyright_year   = 2025

  # Paths copywrite must not add headers to. Anything listed here either carries
  # its own generated header, is not a source file, or would have the comment
  # leak into rendered output.
  header_ignore = [
    # Generated by tools/gen_azurerm_mappings.go, which emits its own header.
    # Stamping this file would also be undone on every regeneration.
    "internal/provider/azurerm_mappings.go",

    # Terraform configuration, documentation templates and the docs they render
    # into. A header here would surface in the published registry documentation.
    "examples/**",
    "templates/**",
    "docs/**",

    # Repository metadata rather than distributed source.
    ".github/**",
  ]
}
