// Code generated by tools/gen_azurerm_mappings.go; DO NOT EDIT.
// Source: https://raw.githubusercontent.com/magodo/aztft/main/internal/resmap/map.json
// Generated: 2026-04-26 20:49:26 UTC
// Run 'make generate-mappings' to regenerate.

package provider

import (
	"strings"
)

// azurermResourceTypeMap maps lowercase AzureNamingTool resource paths to the
// corresponding azurerm Terraform provider resource type name(s).
//
// Keys use the format:
//   - "namespace/resourcetype"           (lowercase, no "Microsoft." prefix)
//   - "namespace/resourcetype/subtype"  (for sub-resources)
//   - "namespace/resourcetype|property" (manual property-specific overrides)
//
// Values are sorted slices of azurerm resource type names. Property-specific
// keys (with the "|property" suffix) are NOT generated automatically — add them
// manually and they will be preserved across regeneration only if managed separately.
//
// Generated from: https://raw.githubusercontent.com/magodo/aztft/main/internal/resmap/map.json
var azurermResourceTypeMap = map[string][]string{
	// AAD
	"aad/domainservices":             {"azurerm_active_directory_domain_service"},
	"aad/domainservices/replicasets": {"azurerm_active_directory_domain_service_replica_set"},

	// AADIAM
	"aadiam/diagnosticsettings": {"azurerm_monitor_aad_diagnostic_setting"},

	// Advisor
	"advisor/recommendations/suppressions": {"azurerm_advisor_suppression"},

	// AlertsManagement
	"alertsmanagement/actionrules": {
		"azurerm_monitor_alert_processing_rule_action_group",
		"azurerm_monitor_alert_processing_rule_suppression",
	},
	"alertsmanagement/prometheusrulegroups":    {"azurerm_monitor_alert_prometheus_rule_group"},
	"alertsmanagement/smartdetectoralertrules": {"azurerm_monitor_smart_detector_alert_rule"},

	// AnalysisServices
	"analysisservices/servers": {"azurerm_analysis_services_server"},

	// ApiManagement
	"apimanagement/gateways":                                {"azurerm_api_management_standalone_gateway"},
	"apimanagement/service":                                 {"azurerm_api_management"},
	"apimanagement/service/apis":                            {"azurerm_api_management_api"},
	"apimanagement/service/apis/diagnostics":                {"azurerm_api_management_api_diagnostic"},
	"apimanagement/service/apis/operations":                 {"azurerm_api_management_api_operation"},
	"apimanagement/service/apis/operations/policies":        {"azurerm_api_management_api_operation_policy"},
	"apimanagement/service/apis/operations/tags":            {"azurerm_api_management_api_operation_tag"},
	"apimanagement/service/apis/policies":                   {"azurerm_api_management_api_policy"},
	"apimanagement/service/apis/releases":                   {"azurerm_api_management_api_release"},
	"apimanagement/service/apis/schemas":                    {"azurerm_api_management_api_schema"},
	"apimanagement/service/apis/tagdescriptions":            {"azurerm_api_management_api_tag_description"},
	"apimanagement/service/apis/tags":                       {"azurerm_api_management_api_tag"},
	"apimanagement/service/apiversionsets":                  {"azurerm_api_management_api_version_set"},
	"apimanagement/service/authorizationservers":            {"azurerm_api_management_authorization_server"},
	"apimanagement/service/backends":                        {"azurerm_api_management_backend"},
	"apimanagement/service/caches":                          {"azurerm_api_management_redis_cache"},
	"apimanagement/service/certificates":                    {"azurerm_api_management_certificate"},
	"apimanagement/service/customdomains":                   {"azurerm_api_management_custom_domain"},
	"apimanagement/service/diagnostics":                     {"azurerm_api_management_diagnostic"},
	"apimanagement/service/gateways":                        {"azurerm_api_management_gateway"},
	"apimanagement/service/gateways/apis":                   {"azurerm_api_management_gateway_api"},
	"apimanagement/service/gateways/certificateauthorities": {"azurerm_api_management_gateway_certificate_authority"},
	"apimanagement/service/gateways/hostnameconfigurations": {"azurerm_api_management_gateway_host_name_configuration"},
	"apimanagement/service/groups":                          {"azurerm_api_management_group"},
	"apimanagement/service/groups/users":                    {"azurerm_api_management_group_user"},
	"apimanagement/service/identityproviders": {
		"azurerm_api_management_identity_provider_aad",
		"azurerm_api_management_identity_provider_aadb2c",
		"azurerm_api_management_identity_provider_facebook",
		"azurerm_api_management_identity_provider_google",
		"azurerm_api_management_identity_provider_microsoft",
		"azurerm_api_management_identity_provider_twitter",
	},
	"apimanagement/service/loggers":                       {"azurerm_api_management_logger"},
	"apimanagement/service/namedvalues":                   {"azurerm_api_management_named_value"},
	"apimanagement/service/notifications/recipientemails": {"azurerm_api_management_notification_recipient_email"},
	"apimanagement/service/notifications/recipientusers":  {"azurerm_api_management_notification_recipient_user"},
	"apimanagement/service/openidconnectproviders":        {"azurerm_api_management_openid_connect_provider"},
	"apimanagement/service/policies":                      {"azurerm_api_management_policy"},
	"apimanagement/service/policyfragments":               {"azurerm_api_management_policy_fragment"},
	"apimanagement/service/products":                      {"azurerm_api_management_product"},
	"apimanagement/service/products/apis":                 {"azurerm_api_management_product_api"},
	"apimanagement/service/products/groups":               {"azurerm_api_management_product_group"},
	"apimanagement/service/products/policies":             {"azurerm_api_management_product_policy"},
	"apimanagement/service/products/tags":                 {"azurerm_api_management_product_tag"},
	"apimanagement/service/schemas":                       {"azurerm_api_management_global_schema"},
	"apimanagement/service/subscriptions":                 {"azurerm_api_management_subscription"},
	"apimanagement/service/tags":                          {"azurerm_api_management_tag"},
	"apimanagement/service/templates":                     {"azurerm_api_management_email_template"},
	"apimanagement/service/users":                         {"azurerm_api_management_user"},
	"apimanagement/service/workspaces":                    {"azurerm_api_management_workspace"},
	"apimanagement/service/workspaces/apiversionsets":     {"azurerm_api_management_workspace_api_version_set"},
	"apimanagement/service/workspaces/certificates":       {"azurerm_api_management_workspace_certificate"},
	"apimanagement/service/workspaces/namedvalues":        {"azurerm_api_management_workspace_named_value"},
	"apimanagement/service/workspaces/policies":           {"azurerm_api_management_workspace_policy"},
	"apimanagement/service/workspaces/policyfragments":    {"azurerm_api_management_workspace_policy_fragment"},

	// App
	"app/containerapps":                           {"azurerm_container_app"},
	"app/containerapps/customdomainname":          {"azurerm_container_app_custom_domain"},
	"app/jobs":                                    {"azurerm_container_app_job"},
	"app/managedenvironments":                     {"azurerm_container_app_environment"},
	"app/managedenvironments/certificates":        {"azurerm_container_app_environment_certificate"},
	"app/managedenvironments/customdomains":       {"azurerm_container_app_environment_custom_domain"},
	"app/managedenvironments/daprcomponents":      {"azurerm_container_app_environment_dapr_component"},
	"app/managedenvironments/managedcertificates": {"azurerm_container_app_environment_managed_certificate"},
	"app/managedenvironments/storages":            {"azurerm_container_app_environment_storage"},

	// AppConfiguration
	"appconfiguration/configurationstores":                               {"azurerm_app_configuration"},
	"appconfiguration/configurationstores/appconfigurationfeature/label": {"azurerm_app_configuration_feature"},
	"appconfiguration/configurationstores/appconfigurationkey/label":     {"azurerm_app_configuration_key"},

	// AppPlatform
	"appplatform/spring":                    {"azurerm_spring_cloud_service"},
	"appplatform/spring/apiportals":         {"azurerm_spring_cloud_api_portal"},
	"appplatform/spring/apiportals/domains": {"azurerm_spring_cloud_api_portal_custom_domain"},
	"appplatform/spring/apms": {
		"azurerm_spring_cloud_app_dynamics_application_performance_monitoring",
		"azurerm_spring_cloud_application_insights_application_performance_monitoring",
		"azurerm_spring_cloud_dynatrace_application_performance_monitoring",
		"azurerm_spring_cloud_elastic_application_performance_monitoring",
		"azurerm_spring_cloud_new_relic_application_performance_monitoring",
	},
	"appplatform/spring/applicationaccelerators":                        {"azurerm_spring_cloud_accelerator"},
	"appplatform/spring/applicationaccelerators/customizedaccelerators": {"azurerm_spring_cloud_customized_accelerator"},
	"appplatform/spring/applicationliveviews":                           {"azurerm_spring_cloud_application_live_view"},
	"appplatform/spring/apps":                                           {"azurerm_spring_cloud_app"},
	"appplatform/spring/apps/bindings": {
		"azurerm_spring_cloud_app_cosmosdb_association",
		"azurerm_spring_cloud_app_mysql_association",
		"azurerm_spring_cloud_app_redis_association",
	},
	"appplatform/spring/apps/deployments": {
		"azurerm_spring_cloud_build_deployment",
		"azurerm_spring_cloud_container_deployment",
		"azurerm_spring_cloud_java_deployment",
	},
	"appplatform/spring/apps/domains":                             {"azurerm_spring_cloud_custom_domain"},
	"appplatform/spring/buildservices/builders":                   {"azurerm_spring_cloud_builder"},
	"appplatform/spring/buildservices/builders/buildpackbindings": {"azurerm_spring_cloud_build_pack_binding"},
	"appplatform/spring/certificates":                             {"azurerm_spring_cloud_certificate"},
	"appplatform/spring/configurationservices":                    {"azurerm_spring_cloud_configuration_service"},
	"appplatform/spring/devtoolportals":                           {"azurerm_spring_cloud_dev_tool_portal"},
	"appplatform/spring/gateways":                                 {"azurerm_spring_cloud_gateway"},
	"appplatform/spring/gateways/domains":                         {"azurerm_spring_cloud_gateway_custom_domain"},
	"appplatform/spring/gateways/routeconfigs":                    {"azurerm_spring_cloud_gateway_route_config"},
	"appplatform/spring/storages":                                 {"azurerm_spring_cloud_storage"},

	// Attestation
	"attestation/attestationproviders": {"azurerm_attestation_provider"},

	// Authorization
	"authorization/locks": {"azurerm_management_lock"},
	"authorization/policyassignments": {
		"azurerm_management_group_policy_assignment",
		"azurerm_resource_group_policy_assignment",
		"azurerm_resource_policy_assignment",
		"azurerm_subscription_policy_assignment",
	},
	"authorization/policydefinitions": {"azurerm_policy_definition"},
	"authorization/policyexemptions": {
		"azurerm_management_group_policy_exemption",
		"azurerm_resource_group_policy_exemption",
		"azurerm_resource_policy_exemption",
		"azurerm_subscription_policy_exemption",
	},
	"authorization/policysetdefinitions": {
		"azurerm_management_group_policy_set_definition",
		"azurerm_policy_set_definition",
	},
	"authorization/privatelinkassociations":        {"azurerm_resource_management_private_link_association"},
	"authorization/resourcemanagementprivatelinks": {"azurerm_resource_management_private_link"},
	"authorization/roleassignments": {
		"azurerm_marketplace_role_assignment",
		"azurerm_role_assignment",
	},
	"authorization/roledefinitions":        {"azurerm_role_definition"},
	"authorization/rolemanagementpolicies": {"azurerm_role_management_policy"},

	// AutoManage
	"automanage/configurationprofileassignments": {
		"azurerm_arc_machine_automanage_configuration_assignment",
		"azurerm_virtual_machine_automanage_configuration_assignment",
	},
	"automanage/configurationprofiles": {"azurerm_automanage_configuration"},

	// Automation
	"automation/automationaccounts":                {"azurerm_automation_account"},
	"automation/automationaccounts/certificates":   {"azurerm_automation_certificate"},
	"automation/automationaccounts/configurations": {"azurerm_automation_dsc_configuration"},
	"automation/automationaccounts/connections": {
		"azurerm_automation_connection",
		"azurerm_automation_connection_certificate",
		"azurerm_automation_connection_classic_certificate",
		"azurerm_automation_connection_service_principal",
	},
	"automation/automationaccounts/connectiontypes":                                {"azurerm_automation_connection_type"},
	"automation/automationaccounts/credentials":                                    {"azurerm_automation_credential"},
	"automation/automationaccounts/hybridrunbookworkergroups":                      {"azurerm_automation_hybrid_runbook_worker_group"},
	"automation/automationaccounts/hybridrunbookworkergroups/hybridrunbookworkers": {"azurerm_automation_hybrid_runbook_worker"},
	"automation/automationaccounts/jobschedules":                                   {"azurerm_automation_job_schedule"},
	"automation/automationaccounts/modules":                                        {"azurerm_automation_module"},
	"automation/automationaccounts/nodeconfigurations":                             {"azurerm_automation_dsc_nodeconfiguration"},
	"automation/automationaccounts/powershell72modules":                            {"azurerm_automation_powershell72_module"},
	"automation/automationaccounts/python3packages":                                {"azurerm_automation_python3_package"},
	"automation/automationaccounts/runbooks":                                       {"azurerm_automation_runbook"},
	"automation/automationaccounts/runtimeenvironments":                            {"azurerm_automation_runtime_environment"},
	"automation/automationaccounts/runtimeenvironments/packages":                   {"azurerm_automation_runtime_environment_package"},
	"automation/automationaccounts/schedules":                                      {"azurerm_automation_schedule"},
	"automation/automationaccounts/softwareupdateconfigurations":                   {"azurerm_automation_software_update_configuration"},
	"automation/automationaccounts/sourcecontrols":                                 {"azurerm_automation_source_control"},
	"automation/automationaccounts/variables": {
		"azurerm_automation_variable_bool",
		"azurerm_automation_variable_datetime",
		"azurerm_automation_variable_int",
		"azurerm_automation_variable_object",
		"azurerm_automation_variable_string",
	},
	"automation/automationaccounts/watchers": {"azurerm_automation_watcher"},
	"automation/automationaccounts/webhooks": {"azurerm_automation_webhook"},

	// AVS
	"avs/privateclouds":                     {"azurerm_vmware_private_cloud"},
	"avs/privateclouds/authorizations":      {"azurerm_vmware_express_route_authorization"},
	"avs/privateclouds/clusters":            {"azurerm_vmware_cluster"},
	"avs/privateclouds/clusters/datastores": {"azurerm_vmware_netapp_volume_attachment"},

	// AzureActiveDirectory
	"azureactivedirectory/b2cdirectories": {"azurerm_aadb2c_directory"},

	// AzureStackHCI
	"azurestackhci/clusters":                        {"azurerm_stack_hci_cluster"},
	"azurestackhci/clusters/arcsettings/extensions": {"azurerm_stack_hci_extension"},
	"azurestackhci/clusters/deploymentsettings":     {"azurerm_stack_hci_deployment_setting"},
	"azurestackhci/logicalnetworks":                 {"azurerm_stack_hci_logical_network"},
	"azurestackhci/marketplacegalleryimages":        {"azurerm_stack_hci_marketplace_gallery_image"},
	"azurestackhci/networkinterfaces":               {"azurerm_stack_hci_network_interface"},
	"azurestackhci/storagecontainers":               {"azurerm_stack_hci_storage_path"},
	"azurestackhci/virtualharddisks":                {"azurerm_stack_hci_virtual_hard_disk"},

	// Batch
	"batch/batchaccounts":              {"azurerm_batch_account"},
	"batch/batchaccounts/applications": {"azurerm_batch_application"},
	"batch/batchaccounts/certificates": {"azurerm_batch_certificate"},
	"batch/batchaccounts/pools":        {"azurerm_batch_pool"},
	"batch/batchaccounts/pools/jobs":   {"azurerm_batch_job"},

	// Blueprint
	"blueprint/blueprintassignments": {"azurerm_blueprint_assignment"},

	// BotService
	"botservice/botservices": {
		"azurerm_bot_channels_registration",
		"azurerm_bot_service_azure_bot",
		"azurerm_bot_web_app",
	},
	"botservice/botservices/channels": {
		"azurerm_bot_channel_alexa",
		"azurerm_bot_channel_direct_line_speech",
		"azurerm_bot_channel_directline",
		"azurerm_bot_channel_email",
		"azurerm_bot_channel_facebook",
		"azurerm_bot_channel_line",
		"azurerm_bot_channel_ms_teams",
		"azurerm_bot_channel_slack",
		"azurerm_bot_channel_sms",
		"azurerm_bot_channel_web_chat",
	},
	"botservice/botservices/connections": {"azurerm_bot_connection"},

	// Cache
	"cache/redis":                                             {"azurerm_redis_cache"},
	"cache/redis/accesspolicies":                              {"azurerm_redis_cache_access_policy"},
	"cache/redis/accesspolicyassignments":                     {"azurerm_redis_cache_access_policy_assignment"},
	"cache/redis/firewallrules":                               {"azurerm_redis_firewall_rule"},
	"cache/redis/linkedservers":                               {"azurerm_redis_linked_server"},
	"cache/redisenterprise/databases/accesspolicyassignments": {"azurerm_managed_redis_access_policy_assignment"},
	"cache/redisenterprise/databasese":                        {"azurerm_managed_redis"},
	"cache/redisenterprise/databasese/replications":           {"azurerm_managed_redis_geo_replication"},

	// Cdn
	"cdn/profiles": {
		"azurerm_cdn_frontdoor_profile",
		"azurerm_cdn_profile",
	},
	"cdn/profiles/afdendpoints":            {"azurerm_cdn_frontdoor_endpoint"},
	"cdn/profiles/afdendpoints/routes":     {"azurerm_cdn_frontdoor_route"},
	"cdn/profiles/associations":            {"azurerm_cdn_frontdoor_custom_domain_association"},
	"cdn/profiles/customdomains":           {"azurerm_cdn_frontdoor_custom_domain"},
	"cdn/profiles/endpoints":               {"azurerm_cdn_endpoint"},
	"cdn/profiles/endpoints/customdomains": {"azurerm_cdn_endpoint_custom_domain"},
	"cdn/profiles/origingroups":            {"azurerm_cdn_frontdoor_origin_group"},
	"cdn/profiles/origingroups/origins":    {"azurerm_cdn_frontdoor_origin"},
	"cdn/profiles/rulesets":                {"azurerm_cdn_frontdoor_rule_set"},
	"cdn/profiles/rulesets/rules":          {"azurerm_cdn_frontdoor_rule"},
	"cdn/profiles/secrets":                 {"azurerm_cdn_frontdoor_secret"},
	"cdn/profiles/securitypolicies":        {"azurerm_cdn_frontdoor_security_policy"},

	// CertificateRegistration
	"certificateregistration/certificateorders": {"azurerm_app_service_certificate_order"},

	// Chaos
	"chaos/experiments":          {"azurerm_chaos_studio_experiment"},
	"chaos/targets":              {"azurerm_chaos_studio_target"},
	"chaos/targets/capabilities": {"azurerm_chaos_studio_capability"},

	// CodeSigning
	"codesigning/codesigningaccounts": {"azurerm_trusted_signing_account"},

	// CognitiveServices
	"cognitiveservices/accounts":               {"azurerm_cognitive_account"},
	"cognitiveservices/accounts/deployments":   {"azurerm_cognitive_deployment"},
	"cognitiveservices/accounts/projects":      {"azurerm_cognitive_account_project"},
	"cognitiveservices/accounts/raiblocklists": {"azurerm_cognitive_account_rai_blocklist"},
	"cognitiveservices/accounts/raipolicies":   {"azurerm_cognitive_account_rai_policy"},

	// Communication
	"communication/communicationservices":                 {"azurerm_communication_service"},
	"communication/emailservices":                         {"azurerm_email_communication_service"},
	"communication/emailservices/domains":                 {"azurerm_email_communication_service_domain"},
	"communication/emailservices/domains/senderusernames": {"azurerm_email_communication_service_domain_sender_username"},

	// Compute
	"compute/availabilitysets":                               {"azurerm_availability_set"},
	"compute/capacityreservationgroups":                      {"azurerm_capacity_reservation_group"},
	"compute/capacityreservationgroups/capacityreservations": {"azurerm_capacity_reservation"},
	"compute/diskaccesses":                                   {"azurerm_disk_access"},
	"compute/diskencryptionsets":                             {"azurerm_disk_encryption_set"},
	"compute/disks":                                          {"azurerm_managed_disk"},
	"compute/galleries":                                      {"azurerm_shared_image_gallery"},
	"compute/galleries/applications":                         {"azurerm_gallery_application"},
	"compute/galleries/applications/versions":                {"azurerm_gallery_application_version"},
	"compute/galleries/images":                               {"azurerm_shared_image"},
	"compute/galleries/images/versions":                      {"azurerm_shared_image_version"},
	"compute/hostgroups":                                     {"azurerm_dedicated_host_group"},
	"compute/hostgroups/hosts":                               {"azurerm_dedicated_host"},
	"compute/images":                                         {"azurerm_image"},
	"compute/proximityplacementgroups":                       {"azurerm_proximity_placement_group"},
	"compute/restorepointcollections":                        {"azurerm_virtual_machine_restore_point_collection"},
	"compute/restorepointcollections/restorepoints":          {"azurerm_virtual_machine_restore_point"},
	"compute/snapshots":                                      {"azurerm_snapshot"},
	"compute/sshpublickeys":                                  {"azurerm_ssh_public_key"},
	"compute/virtualmachines": {
		"azurerm_linux_virtual_machine",
		"azurerm_virtual_machine",
		"azurerm_windows_virtual_machine",
	},
	"compute/virtualmachines/datadisks": {
		"azurerm_virtual_machine_data_disk_attachment",
		"azurerm_virtual_machine_implicit_data_disk_from_source",
	},
	"compute/virtualmachines/extensions":  {"azurerm_virtual_machine_extension"},
	"compute/virtualmachines/runcommands": {"azurerm_virtual_machine_run_command"},
	"compute/virtualmachinescalesets": {
		"azurerm_linux_virtual_machine_scale_set",
		"azurerm_orchestrated_virtual_machine_scale_set",
		"azurerm_windows_virtual_machine_scale_set",
	},
	"compute/virtualmachinescalesets/extensions": {"azurerm_virtual_machine_scale_set_extension"},

	// ConfidentialLedger
	"confidentialledger/ledgers": {"azurerm_confidential_ledger"},

	// Consumption
	"consumption/budgets": {
		"azurerm_consumption_budget_management_group",
		"azurerm_consumption_budget_resource_group",
		"azurerm_consumption_budget_subscription",
	},

	// ContainerInstance
	"containerinstance/containergroups": {"azurerm_container_group"},

	// ContainerRegistry
	"containerregistry/registries":                     {"azurerm_container_registry"},
	"containerregistry/registries/agentpools":          {"azurerm_container_registry_agent_pool"},
	"containerregistry/registries/cacherules":          {"azurerm_container_registry_cache_rule"},
	"containerregistry/registries/connectedregistries": {"azurerm_container_connected_registry"},
	"containerregistry/registries/credentialsets":      {"azurerm_container_registry_credential_set"},
	"containerregistry/registries/scopemaps":           {"azurerm_container_registry_scope_map"},
	"containerregistry/registries/tasks":               {"azurerm_container_registry_task"},
	"containerregistry/registries/tokens":              {"azurerm_container_registry_token"},
	"containerregistry/registries/tokens/passwords":    {"azurerm_container_registry_token_password"},
	"containerregistry/registries/webhooks":            {"azurerm_container_registry_webhook"},

	// ContainerService
	"containerservice/deploymentsafeguards":                      {"azurerm_kubernetes_cluster_deployment_safeguard"},
	"containerservice/fleets":                                    {"azurerm_kubernetes_fleet_manager"},
	"containerservice/fleets/members":                            {"azurerm_kubernetes_fleet_member"},
	"containerservice/fleets/updateruns":                         {"azurerm_kubernetes_fleet_update_run"},
	"containerservice/fleets/updatestrategies":                   {"azurerm_kubernetes_fleet_update_strategy"},
	"containerservice/managedclusters":                           {"azurerm_kubernetes_cluster"},
	"containerservice/managedclusters/agentpools":                {"azurerm_kubernetes_cluster_node_pool"},
	"containerservice/managedclusters/trustedaccessrolebindings": {"azurerm_kubernetes_cluster_trusted_access_role_binding"},

	// CostManagement
	"costmanagement/exports": {
		"azurerm_billing_account_cost_management_export",
		"azurerm_resource_group_cost_management_export",
		"azurerm_subscription_cost_management_export",
	},
	"costmanagement/scheduledactions": {
		"azurerm_cost_anomaly_alert",
		"azurerm_cost_management_scheduled_action",
	},
	"costmanagement/views": {
		"azurerm_resource_group_cost_management_view",
		"azurerm_subscription_cost_management_view",
	},

	// CustomProviders
	"customproviders/resourceproviders": {"azurerm_custom_provider"},

	// Dashboard
	"dashboard/grafana":                         {"azurerm_dashboard_grafana"},
	"dashboard/grafana/managedprivateendpoints": {"azurerm_dashboard_grafana_managed_private_endpoint"},

	// DataBoxEdge
	"databoxedge/databoxedgedevices": {"azurerm_databox_edge_device"},

	// Databricks
	"databricks/accessconnectors":                  {"azurerm_databricks_access_connector"},
	"databricks/workspaces":                        {"azurerm_databricks_workspace"},
	"databricks/workspaces/virtualnetworkpeerings": {"azurerm_databricks_virtual_network_peering"},

	// Datadog
	"datadog/monitors": {"azurerm_datadog_monitor"},
	"datadog/monitors/singlesignonconfigurations": {"azurerm_datadog_monitor_sso_configuration"},
	"datadog/monitors/tagrules":                   {"azurerm_datadog_monitor_tag_rule"},

	// DataFactory
	"datafactory/factories": {"azurerm_data_factory"},
	"datafactory/factories/credentials": {
		"azurerm_data_factory_credential_service_principal",
		"azurerm_data_factory_credential_user_managed_identity",
	},
	"datafactory/factories/dataflows": {
		"azurerm_data_factory_data_flow",
		"azurerm_data_factory_flowlet_data_flow",
	},
	"datafactory/factories/datasets": {
		"azurerm_data_factory_custom_dataset",
		"azurerm_data_factory_dataset_azure_blob",
		"azurerm_data_factory_dataset_azure_sql_table",
		"azurerm_data_factory_dataset_binary",
		"azurerm_data_factory_dataset_cosmosdb_sqlapi",
		"azurerm_data_factory_dataset_delimited_text",
		"azurerm_data_factory_dataset_http",
		"azurerm_data_factory_dataset_json",
		"azurerm_data_factory_dataset_mysql",
		"azurerm_data_factory_dataset_parquet",
		"azurerm_data_factory_dataset_postgresql",
		"azurerm_data_factory_dataset_snowflake",
		"azurerm_data_factory_dataset_sql_server_table",
	},
	"datafactory/factories/integrationruntimes": {
		"azurerm_data_factory_integration_runtime_azure",
		"azurerm_data_factory_integration_runtime_azure_ssis",
		"azurerm_data_factory_integration_runtime_self_hosted",
	},
	"datafactory/factories/linkedservices": {
		"azurerm_data_factory_linked_custom_service",
		"azurerm_data_factory_linked_service_azure_blob_storage",
		"azurerm_data_factory_linked_service_azure_databricks",
		"azurerm_data_factory_linked_service_azure_file_storage",
		"azurerm_data_factory_linked_service_azure_function",
		"azurerm_data_factory_linked_service_azure_search",
		"azurerm_data_factory_linked_service_azure_sql_database",
		"azurerm_data_factory_linked_service_azure_table_storage",
		"azurerm_data_factory_linked_service_cosmosdb",
		"azurerm_data_factory_linked_service_cosmosdb_mongoapi",
		"azurerm_data_factory_linked_service_data_lake_storage_gen2",
		"azurerm_data_factory_linked_service_key_vault",
		"azurerm_data_factory_linked_service_kusto",
		"azurerm_data_factory_linked_service_mysql",
		"azurerm_data_factory_linked_service_odata",
		"azurerm_data_factory_linked_service_odbc",
		"azurerm_data_factory_linked_service_postgresql",
		"azurerm_data_factory_linked_service_sftp",
		"azurerm_data_factory_linked_service_snowflake",
		"azurerm_data_factory_linked_service_sql_managed_instance",
		"azurerm_data_factory_linked_service_sql_server",
		"azurerm_data_factory_linked_service_synapse",
		"azurerm_data_factory_linked_service_web",
	},
	"datafactory/factories/managedvirtualnetworks/managedprivateendpoints": {"azurerm_data_factory_managed_private_endpoint"},
	"datafactory/factories/pipelines":                                      {"azurerm_data_factory_pipeline"},
	"datafactory/factories/triggers": {
		"azurerm_data_factory_trigger_blob_event",
		"azurerm_data_factory_trigger_custom_event",
		"azurerm_data_factory_trigger_schedule",
		"azurerm_data_factory_trigger_tumbling_window",
	},

	// DataMigration
	"datamigration/services":          {"azurerm_database_migration_service"},
	"datamigration/services/projects": {"azurerm_database_migration_project"},

	// DataProtection
	"dataprotection/backupvaults": {"azurerm_data_protection_backup_vault"},
	"dataprotection/backupvaults/backupinstances": {
		"azurerm_data_protection_backup_instance_blob_storage",
		"azurerm_data_protection_backup_instance_data_lake_storage",
		"azurerm_data_protection_backup_instance_disk",
		"azurerm_data_protection_backup_instance_kubernetes_cluster",
		"azurerm_data_protection_backup_instance_mysql_flexible_server",
		"azurerm_data_protection_backup_instance_postgresql",
		"azurerm_data_protection_backup_instance_postgresql_flexible_server",
	},
	"dataprotection/backupvaults/backuppolicies": {
		"azurerm_data_protection_backup_policy_blob_storage",
		"azurerm_data_protection_backup_policy_data_lake_storage",
		"azurerm_data_protection_backup_policy_disk",
		"azurerm_data_protection_backup_policy_kubernetes_cluster",
		"azurerm_data_protection_backup_policy_mysql_flexible_server",
		"azurerm_data_protection_backup_policy_postgresql",
		"azurerm_data_protection_backup_policy_postgresql_flexible_server",
	},
	"dataprotection/resourceguards": {"azurerm_data_protection_resource_guard"},

	// DataShare
	"datashare/accounts":        {"azurerm_data_share_account"},
	"datashare/accounts/shares": {"azurerm_data_share"},
	"datashare/accounts/shares/datasets": {
		"azurerm_data_share_dataset_blob_storage",
		"azurerm_data_share_dataset_data_lake_gen2",
		"azurerm_data_share_dataset_kusto_cluster",
		"azurerm_data_share_dataset_kusto_database",
	},

	// DBforMySQL
	"dbformysql/flexibleservers":                {"azurerm_mysql_flexible_server"},
	"dbformysql/flexibleservers/administrators": {"azurerm_mysql_flexible_server_active_directory_administrator"},
	"dbformysql/flexibleservers/configurations": {"azurerm_mysql_flexible_server_configuration"},
	"dbformysql/flexibleservers/databases":      {"azurerm_mysql_flexible_database"},
	"dbformysql/flexibleservers/firewallrules":  {"azurerm_mysql_flexible_server_firewall_rule"},

	// DBforPostgreSQL
	"dbforpostgresql/flexibleservers":                          {"azurerm_postgresql_flexible_server"},
	"dbforpostgresql/flexibleservers/administrators":           {"azurerm_postgresql_flexible_server_active_directory_administrator"},
	"dbforpostgresql/flexibleservers/backups":                  {"azurerm_postgresql_flexible_server_backup"},
	"dbforpostgresql/flexibleservers/configurations":           {"azurerm_postgresql_flexible_server_configuration"},
	"dbforpostgresql/flexibleservers/databases":                {"azurerm_postgresql_flexible_server_database"},
	"dbforpostgresql/flexibleservers/firewallrules":            {"azurerm_postgresql_flexible_server_firewall_rule"},
	"dbforpostgresql/flexibleservers/virtualendpoints":         {"azurerm_postgresql_flexible_server_virtual_endpoint"},
	"dbforpostgresql/servergroupsv2":                           {"azurerm_cosmosdb_postgresql_cluster"},
	"dbforpostgresql/servergroupsv2/coordinatorconfigurations": {"azurerm_cosmosdb_postgresql_coordinator_configuration"},
	"dbforpostgresql/servergroupsv2/firewallrules":             {"azurerm_cosmosdb_postgresql_firewall_rule"},
	"dbforpostgresql/servergroupsv2/nodeconfigurations":        {"azurerm_cosmosdb_postgresql_node_configuration"},
	"dbforpostgresql/servergroupsv2/roles":                     {"azurerm_cosmosdb_postgresql_role"},
	"dbforpostgresql/servers":                                  {"azurerm_postgresql_server"},
	"dbforpostgresql/servers/administrators":                   {"azurerm_postgresql_active_directory_administrator"},
	"dbforpostgresql/servers/configurations":                   {"azurerm_postgresql_configuration"},
	"dbforpostgresql/servers/databases":                        {"azurerm_postgresql_database"},
	"dbforpostgresql/servers/firewallrules":                    {"azurerm_postgresql_firewall_rule"},
	"dbforpostgresql/servers/keys":                             {"azurerm_postgresql_server_key"},
	"dbforpostgresql/servers/virtualnetworkrules":              {"azurerm_postgresql_virtual_network_rule"},

	// DesktopVirtualization
	"desktopvirtualization/applicationgroups":              {"azurerm_virtual_desktop_application_group"},
	"desktopvirtualization/applicationgroups/applications": {"azurerm_virtual_desktop_application"},
	"desktopvirtualization/hostpools":                      {"azurerm_virtual_desktop_host_pool"},
	"desktopvirtualization/hostpools/registrationinfo":     {"azurerm_virtual_desktop_host_pool_registration_info"},
	"desktopvirtualization/scalingplans":                   {"azurerm_virtual_desktop_scaling_plan"},
	"desktopvirtualization/workspaces":                     {"azurerm_virtual_desktop_workspace"},
	"desktopvirtualization/workspaces/applicationgroups":   {"azurerm_virtual_desktop_workspace_application_group_association"},

	// DevCenter
	"devcenter/devcenters":                   {"azurerm_dev_center"},
	"devcenter/devcenters/attachednetworks":  {"azurerm_dev_center_attached_network"},
	"devcenter/devcenters/catalogs":          {"azurerm_dev_center_catalog"},
	"devcenter/devcenters/devboxdefinitions": {"azurerm_dev_center_dev_box_definition"},
	"devcenter/devcenters/environmenttypes":  {"azurerm_dev_center_environment_type"},
	"devcenter/devcenters/galleries":         {"azurerm_dev_center_gallery"},
	"devcenter/networkconnections":           {"azurerm_dev_center_network_connection"},
	"devcenter/projects":                     {"azurerm_dev_center_project"},
	"devcenter/projects/environmenttypes":    {"azurerm_dev_center_project_environment_type"},
	"devcenter/projects/pools":               {"azurerm_dev_center_project_pool"},

	// Devices
	"devices/iothubs":                                  {"azurerm_iothub"},
	"devices/iothubs/certificates":                     {"azurerm_iothub_certificate"},
	"devices/iothubs/endpointscosmosdbaccount":         {"azurerm_iothub_endpoint_cosmosdb_account"},
	"devices/iothubs/endpointseventhub":                {"azurerm_iothub_endpoint_eventhub"},
	"devices/iothubs/endpointsservicebusqueue":         {"azurerm_iothub_endpoint_servicebus_queue"},
	"devices/iothubs/endpointsservicebustopic":         {"azurerm_iothub_endpoint_servicebus_topic"},
	"devices/iothubs/endpointsstoragecontainer":        {"azurerm_iothub_endpoint_storage_container"},
	"devices/iothubs/enrichments":                      {"azurerm_iothub_enrichment"},
	"devices/iothubs/eventhubendpoints/consumergroups": {"azurerm_iothub_consumer_group"},
	"devices/iothubs/fallbackroute":                    {"azurerm_iothub_fallback_route"},
	"devices/iothubs/iothubkeys":                       {"azurerm_iothub_shared_access_policy"},
	"devices/iothubs/routes":                           {"azurerm_iothub_route"},
	"devices/provisioningservices":                     {"azurerm_iothub_dps"},
	"devices/provisioningservices/certificates":        {"azurerm_iothub_dps_certificate"},
	"devices/provisioningservices/keys":                {"azurerm_iothub_dps_shared_access_policy"},

	// DeviceUpdate
	"deviceupdate/accounts":           {"azurerm_iothub_device_update_account"},
	"deviceupdate/accounts/instances": {"azurerm_iothub_device_update_instance"},

	// DevOpsInfrastructure
	"devopsinfrastructure/pools": {"azurerm_managed_devops_pool"},

	// DevTestLab
	"devtestlab/labs":                     {"azurerm_dev_test_lab"},
	"devtestlab/labs/policysets/policies": {"azurerm_dev_test_policy"},
	"devtestlab/labs/schedules":           {"azurerm_dev_test_schedule"},
	"devtestlab/labs/virtualmachines": {
		"azurerm_dev_test_linux_virtual_machine",
		"azurerm_dev_test_windows_virtual_machine",
	},
	"devtestlab/labs/virtualnetworks": {"azurerm_dev_test_virtual_network"},
	"devtestlab/schedules":            {"azurerm_dev_test_global_vm_shutdown_schedule"},

	// DigitalTwins
	"digitaltwins/digitaltwinsinstances": {"azurerm_digital_twins_instance"},
	"digitaltwins/digitaltwinsinstances/endpoints": {
		"azurerm_digital_twins_endpoint_eventgrid",
		"azurerm_digital_twins_endpoint_eventhub",
		"azurerm_digital_twins_endpoint_servicebus",
	},
	"digitaltwins/digitaltwinsinstances/timeseriesdatabaseconnections": {"azurerm_digital_twins_time_series_database_connection"},

	// DocumentDB
	"documentdb/cassandraclusters":                                             {"azurerm_cosmosdb_cassandra_cluster"},
	"documentdb/cassandraclusters/datacenters":                                 {"azurerm_cosmosdb_cassandra_datacenter"},
	"documentdb/databaseaccounts":                                              {"azurerm_cosmosdb_account"},
	"documentdb/databaseaccounts/cassandrakeyspaces":                           {"azurerm_cosmosdb_cassandra_keyspace"},
	"documentdb/databaseaccounts/cassandrakeyspaces/tables":                    {"azurerm_cosmosdb_cassandra_table"},
	"documentdb/databaseaccounts/gremlindatabases":                             {"azurerm_cosmosdb_gremlin_database"},
	"documentdb/databaseaccounts/gremlindatabases/graphs":                      {"azurerm_cosmosdb_gremlin_graph"},
	"documentdb/databaseaccounts/mongodbdatabases":                             {"azurerm_cosmosdb_mongo_database"},
	"documentdb/databaseaccounts/mongodbdatabases/collections":                 {"azurerm_cosmosdb_mongo_collection"},
	"documentdb/databaseaccounts/mongodbroledefinitions":                       {"azurerm_cosmosdb_mongo_role_definition"},
	"documentdb/databaseaccounts/mongodbuserdefinitions":                       {"azurerm_cosmosdb_mongo_user_definition"},
	"documentdb/databaseaccounts/services":                                     {"azurerm_cosmosdb_sql_dedicated_gateway"},
	"documentdb/databaseaccounts/sqldatabases":                                 {"azurerm_cosmosdb_sql_database"},
	"documentdb/databaseaccounts/sqldatabases/containers":                      {"azurerm_cosmosdb_sql_container"},
	"documentdb/databaseaccounts/sqldatabases/containers/storedprocedures":     {"azurerm_cosmosdb_sql_stored_procedure"},
	"documentdb/databaseaccounts/sqldatabases/containers/triggers":             {"azurerm_cosmosdb_sql_trigger"},
	"documentdb/databaseaccounts/sqldatabases/containers/userdefinedfunctions": {"azurerm_cosmosdb_sql_function"},
	"documentdb/databaseaccounts/sqlroleassignments":                           {"azurerm_cosmosdb_sql_role_assignment"},
	"documentdb/databaseaccounts/sqlroledefinitions":                           {"azurerm_cosmosdb_sql_role_definition"},
	"documentdb/databaseaccounts/tables":                                       {"azurerm_cosmosdb_table"},
	"documentdb/mongoclusters":                                                 {"azurerm_mongo_cluster"},
	"documentdb/mongoclusters/firewallrules":                                   {"azurerm_mongo_cluster_firewall_rule"},
	"documentdb/mongoclusters/users":                                           {"azurerm_mongo_cluster_user"},

	// Dynatrace.Observability
	"dynatrace.observability/monitors/tagrules": {"azurerm_dynatrace_tag_rules"},

	// Elastic
	"elastic/monitors": {"azurerm_elastic_cloud_elasticsearch"},

	// ElasticSan
	"elasticsan/elasticsans":                      {"azurerm_elastic_san"},
	"elasticsan/elasticsans/volumegroups":         {"azurerm_elastic_san_volume_group"},
	"elasticsan/elasticsans/volumegroups/volumes": {"azurerm_elastic_san_volume"},

	// EventGrid
	"eventgrid/domains":                         {"azurerm_eventgrid_domain"},
	"eventgrid/domains/topics":                  {"azurerm_eventgrid_domain_topic"},
	"eventgrid/eventsubscriptions":              {"azurerm_eventgrid_event_subscription"},
	"eventgrid/namespaces":                      {"azurerm_eventgrid_namespace"},
	"eventgrid/namespaces/topics":               {"azurerm_eventgrid_namespace_topic"},
	"eventgrid/partnerconfigurations":           {"azurerm_eventgrid_partner_configuration"},
	"eventgrid/partnernamespaces":               {"azurerm_eventgrid_partner_namespace"},
	"eventgrid/partnerregistrations":            {"azurerm_eventgrid_partner_registration"},
	"eventgrid/systemtopics":                    {"azurerm_eventgrid_system_topic"},
	"eventgrid/systemtopics/eventsubscriptions": {"azurerm_eventgrid_system_topic_event_subscription"},
	"eventgrid/topics":                          {"azurerm_eventgrid_topic"},

	// EventHub
	"eventhub/clusters":                                {"azurerm_eventhub_cluster"},
	"eventhub/namespaces":                              {"azurerm_eventhub_namespace"},
	"eventhub/namespaces/authorizationrules":           {"azurerm_eventhub_namespace_authorization_rule"},
	"eventhub/namespaces/disasterrecoveryconfigs":      {"azurerm_eventhub_namespace_disaster_recovery_config"},
	"eventhub/namespaces/eventhubs":                    {"azurerm_eventhub"},
	"eventhub/namespaces/eventhubs/authorizationrules": {"azurerm_eventhub_authorization_rule"},
	"eventhub/namespaces/eventhubs/consumergroups":     {"azurerm_eventhub_consumer_group"},
	"eventhub/namespaces/schemagroups":                 {"azurerm_eventhub_namespace_schema_group"},

	// ExtendedLocation
	"extendedlocation/customlocations": {"azurerm_extended_location_custom_location"},

	// Fabric
	"fabric/capacities": {"azurerm_fabric_capacity"},

	// FluidRelay
	"fluidrelay/fluidrelayservers": {"azurerm_fluid_relay_server"},

	// GraphServices
	"graphservices/accounts": {"azurerm_graph_services_account"},

	// GuestConfiguration
	"guestconfiguration/guestconfigurationassignments": {"azurerm_policy_virtual_machine_configuration_assignment"},

	// HardwareSecurityModules
	"hardwaresecuritymodules/dedicatedhsms": {"azurerm_dedicated_hardware_security_module"},

	// HDInsight
	"hdinsight/clusters": {
		"azurerm_hdinsight_hadoop_cluster",
		"azurerm_hdinsight_hbase_cluster",
		"azurerm_hdinsight_interactive_query_cluster",
		"azurerm_hdinsight_kafka_cluster",
		"azurerm_hdinsight_spark_cluster",
	},

	// HealthBot
	"healthbot/healthbots": {"azurerm_healthbot"},

	// HealthcareApis
	"healthcareapis/services":                                  {"azurerm_healthcare_service"},
	"healthcareapis/workspaces":                                {"azurerm_healthcare_workspace"},
	"healthcareapis/workspaces/dicomservices":                  {"azurerm_healthcare_dicom_service"},
	"healthcareapis/workspaces/fhirservices":                   {"azurerm_healthcare_fhir_service"},
	"healthcareapis/workspaces/iotconnectors":                  {"azurerm_healthcare_medtech_service"},
	"healthcareapis/workspaces/iotconnectors/fhirdestinations": {"azurerm_healthcare_medtech_service_fhir_destination"},

	// HybridCompute
	"hybridcompute/machines":            {"azurerm_arc_machine"},
	"hybridcompute/machines/extensions": {"azurerm_arc_machine_extension"},
	"hybridcompute/privatelinkscopes":   {"azurerm_arc_private_link_scope"},

	// Insights
	"insights/actiongroups":                         {"azurerm_monitor_action_group"},
	"insights/activitylogalerts":                    {"azurerm_monitor_activity_log_alert"},
	"insights/autoscalesettings":                    {"azurerm_monitor_autoscale_setting"},
	"insights/components":                           {"azurerm_application_insights"},
	"insights/components/analyticsitems":            {"azurerm_application_insights_analytics_item"},
	"insights/components/apikeys":                   {"azurerm_application_insights_api_key"},
	"insights/components/proactivedetectionconfigs": {"azurerm_application_insights_smart_detection_rule"},
	"insights/datacollectionendpoints":              {"azurerm_monitor_data_collection_endpoint"},
	"insights/datacollectionruleassociations":       {"azurerm_monitor_data_collection_rule_association"},
	"insights/datacollectionrules":                  {"azurerm_monitor_data_collection_rule"},
	"insights/diagnosticsettings":                   {"azurerm_monitor_diagnostic_setting"},
	"insights/metricalerts":                         {"azurerm_monitor_metric_alert"},
	"insights/privatelinkscopes":                    {"azurerm_monitor_private_link_scope"},
	"insights/privatelinkscopes/scopedresources":    {"azurerm_monitor_private_link_scoped_service"},
	"insights/scheduledqueryrules":                  {"azurerm_monitor_scheduled_query_rules_alert_v2"},
	"insights/webtests": {
		"azurerm_application_insights_standard_web_test",
		"azurerm_application_insights_web_test",
	},
	"insights/workbooks":         {"azurerm_application_insights_workbook"},
	"insights/workbooktemplates": {"azurerm_application_insights_workbook_template"},

	// IoTCentral
	"iotcentral/iotapps":                 {"azurerm_iotcentral_application"},
	"iotcentral/iotapps/networkrulesets": {"azurerm_iotcentral_application_network_rule_set"},
	"iotcentral/iotapps/organizations":   {"azurerm_iotcentral_organization"},

	// KeyVault
	"keyvault/managedhsms":                  {"azurerm_key_vault_managed_hardware_security_module"},
	"keyvault/vaults":                       {"azurerm_key_vault"},
	"keyvault/vaults/certificates":          {"azurerm_key_vault_certificate"},
	"keyvault/vaults/certificates/contacts": {"azurerm_key_vault_certificate_contacts"},
	"keyvault/vaults/certificates/issuers":  {"azurerm_key_vault_certificate_issuer"},
	"keyvault/vaults/keys":                  {"azurerm_key_vault_key"},
	"keyvault/vaults/objectid":              {"azurerm_key_vault_access_policy"},
	"keyvault/vaults/secrets":               {"azurerm_key_vault_secret"},
	"keyvault/vaults/storage":               {"azurerm_key_vault_managed_storage_account"},
	"keyvault/vaults/storage/sas":           {"azurerm_key_vault_managed_storage_account_sas_token_definition"},

	// Kubernetes
	"kubernetes/connectedclusters": {
		"azurerm_arc_kubernetes_cluster",
		"azurerm_arc_kubernetes_provisioned_cluster",
	},

	// KubernetesConfiguration
	"kubernetesconfiguration/extensions": {
		"azurerm_arc_kubernetes_cluster_extension",
		"azurerm_kubernetes_cluster_extension",
	},
	"kubernetesconfiguration/fluxconfigurations": {
		"azurerm_arc_kubernetes_flux_configuration",
		"azurerm_kubernetes_flux_configuration",
	},

	// Kusto
	"kusto/clusters": {"azurerm_kusto_cluster"},
	"kusto/clusters/attacheddatabaseconfigurations": {"azurerm_kusto_attached_database_configuration"},
	"kusto/clusters/databases":                      {"azurerm_kusto_database"},
	"kusto/clusters/databases/dataconnections": {
		"azurerm_kusto_cosmosdb_data_connection",
		"azurerm_kusto_eventgrid_data_connection",
		"azurerm_kusto_eventhub_data_connection",
		"azurerm_kusto_iothub_data_connection",
	},
	"kusto/clusters/databases/principalassignments": {"azurerm_kusto_database_principal_assignment"},
	"kusto/clusters/databases/scripts":              {"azurerm_kusto_script"},
	"kusto/clusters/managedprivateendpoints":        {"azurerm_kusto_cluster_managed_private_endpoint"},
	"kusto/clusters/principalassignments":           {"azurerm_kusto_cluster_principal_assignment"},

	// LoadTestService
	"loadtestservice/loadtests": {"azurerm_load_test"},

	// Logic
	"logic/integrationaccounts":                     {"azurerm_logic_app_integration_account"},
	"logic/integrationaccounts/agreements":          {"azurerm_logic_app_integration_account_agreement"},
	"logic/integrationaccounts/assemblies":          {"azurerm_logic_app_integration_account_assembly"},
	"logic/integrationaccounts/batchconfigurations": {"azurerm_logic_app_integration_account_batch_configuration"},
	"logic/integrationaccounts/certificates":        {"azurerm_logic_app_integration_account_certificate"},
	"logic/integrationaccounts/maps":                {"azurerm_logic_app_integration_account_map"},
	"logic/integrationaccounts/partners":            {"azurerm_logic_app_integration_account_partner"},
	"logic/integrationaccounts/schemas":             {"azurerm_logic_app_integration_account_schema"},
	"logic/integrationaccounts/sessions":            {"azurerm_logic_app_integration_account_session"},
	"logic/workflows":                               {"azurerm_logic_app_workflow"},
	"logic/workflows/actions": {
		"azurerm_logic_app_action_custom",
		"azurerm_logic_app_action_http",
	},
	"logic/workflows/triggers": {
		"azurerm_logic_app_trigger_custom",
		"azurerm_logic_app_trigger_http_request",
		"azurerm_logic_app_trigger_recurrence",
	},

	// MachineLearningServices
	"machinelearningservices/workspaces": {
		"azurerm_ai_foundry",
		"azurerm_ai_foundry_project",
		"azurerm_machine_learning_workspace",
	},
	"machinelearningservices/workspaces/computes": {
		"azurerm_machine_learning_compute_cluster",
		"azurerm_machine_learning_compute_instance",
		"azurerm_machine_learning_inference_cluster",
		"azurerm_machine_learning_synapse_spark",
	},
	"machinelearningservices/workspaces/datastores": {
		"azurerm_machine_learning_datastore_blobstorage",
		"azurerm_machine_learning_datastore_datalake_gen2",
		"azurerm_machine_learning_datastore_fileshare",
	},
	"machinelearningservices/workspaces/outboundrules": {
		"azurerm_machine_learning_workspace_network_outbound_rule_fqdn",
		"azurerm_machine_learning_workspace_network_outbound_rule_private_endpoint",
		"azurerm_machine_learning_workspace_network_outbound_rule_service_tag",
	},

	// Maintenance
	"maintenance/configurationassignments": {
		"azurerm_maintenance_assignment_dedicated_host",
		"azurerm_maintenance_assignment_dynamic_scope",
		"azurerm_maintenance_assignment_virtual_machine",
		"azurerm_maintenance_assignment_virtual_machine_scale_set",
	},
	"maintenance/maintenanceconfigurations": {"azurerm_maintenance_configuration"},

	// ManagedIdentity
	"managedidentity/userassignedidentities":                              {"azurerm_user_assigned_identity"},
	"managedidentity/userassignedidentities/federatedidentitycredentials": {"azurerm_federated_identity_credential"},

	// ManagedServices
	"managedservices/registrationassignments": {"azurerm_lighthouse_assignment"},
	"managedservices/registrationdefinitions": {"azurerm_lighthouse_definition"},

	// Management
	"management/managementgroups": {"azurerm_management_group"},

	// Maps
	"maps/accounts":          {"azurerm_maps_account"},
	"maps/accounts/creators": {"azurerm_maps_creator"},

	// MarketplaceOrdering
	"marketplaceordering/agreements/offers/plans": {"azurerm_marketplace_agreement"},

	// Monitor
	"monitor/accounts": {"azurerm_monitor_workspace"},

	// NetApp
	"netapp/netappaccounts":                                        {"azurerm_netapp_account"},
	"netapp/netappaccounts/backuppolicies":                         {"azurerm_netapp_backup_policy"},
	"netapp/netappaccounts/backupvaults":                           {"azurerm_netapp_backup_vault"},
	"netapp/netappaccounts/capacitypools":                          {"azurerm_netapp_pool"},
	"netapp/netappaccounts/capacitypools/volumes":                  {"azurerm_netapp_volume"},
	"netapp/netappaccounts/capacitypools/volumes/snapshots":        {"azurerm_netapp_snapshot"},
	"netapp/netappaccounts/capacitypools/volumes/volumequotarules": {"azurerm_netapp_volume_quota_rule"},
	"netapp/netappaccounts/encryptions":                            {"azurerm_netapp_account_encryption"},
	"netapp/netappaccounts/snapshotpolicies":                       {"azurerm_netapp_snapshot_policy"},
	"netapp/netappaccounts/volumegroups": {
		"azurerm_netapp_volume_group_oracle",
		"azurerm_netapp_volume_group_sap_hana",
	},

	// Network
	"network/applicationgateways":                              {"azurerm_application_gateway"},
	"network/applicationgateways/backendaddresspools":          {"fake_azurerm_application_gateway_backend_address_pool"},
	"network/applicationgatewaywebapplicationfirewallpolicies": {"azurerm_web_application_firewall_policy"},
	"network/applicationsecuritygroups":                        {"azurerm_application_security_group"},
	"network/azurefirewalls":                                   {"azurerm_firewall"},
	"network/azurefirewalls/applicationrulecollections":        {"azurerm_firewall_application_rule_collection"},
	"network/azurefirewalls/natrulecollections":                {"azurerm_firewall_nat_rule_collection"},
	"network/azurefirewalls/networkrulecollections":            {"azurerm_firewall_network_rule_collection"},
	"network/bastionhosts":                                     {"azurerm_bastion_host"},
	"network/connections":                                      {"azurerm_virtual_network_gateway_connection"},
	"network/customipprefixes":                                 {"azurerm_custom_ip_prefix"},
	"network/ddosprotectionplans":                              {"azurerm_network_ddos_protection_plan"},
	"network/dnsforwardingrulesets":                            {"azurerm_private_dns_resolver_dns_forwarding_ruleset"},
	"network/dnsforwardingrulesets/forwardingrules":            {"azurerm_private_dns_resolver_forwarding_rule"},
	"network/dnsforwardingrulesets/virtualnetworklinks":        {"azurerm_private_dns_resolver_virtual_network_link"},
	"network/dnsresolvers":                                     {"azurerm_private_dns_resolver"},
	"network/dnsresolvers/inboundendpoints":                    {"azurerm_private_dns_resolver_inbound_endpoint"},
	"network/dnsresolvers/outboundendpoints":                   {"azurerm_private_dns_resolver_outbound_endpoint"},
	"network/dnszones":                                         {"azurerm_dns_zone"},
	"network/dnszones/a":                                       {"azurerm_dns_a_record"},
	"network/dnszones/aaaa":                                    {"azurerm_dns_aaaa_record"},
	"network/dnszones/caa":                                     {"azurerm_dns_caa_record"},
	"network/dnszones/cname":                                   {"azurerm_dns_cname_record"},
	"network/dnszones/mx":                                      {"azurerm_dns_mx_record"},
	"network/dnszones/ns":                                      {"azurerm_dns_ns_record"},
	"network/dnszones/ptr":                                     {"azurerm_dns_ptr_record"},
	"network/dnszones/srv":                                     {"azurerm_dns_srv_record"},
	"network/dnszones/txt":                                     {"azurerm_dns_txt_record"},
	"network/expressroutecircuits":                             {"azurerm_express_route_circuit"},
	"network/expressroutecircuits/authorizations":              {"azurerm_express_route_circuit_authorization"},
	"network/expressroutecircuits/peerings":                    {"azurerm_express_route_circuit_peering"},
	"network/expressroutecircuits/peerings/connections":        {"azurerm_express_route_circuit_connection"},
	"network/expressroutegateways":                             {"azurerm_express_route_gateway"},
	"network/expressroutegateways/expressrouteconnections":     {"azurerm_express_route_connection"},
	"network/expressrouteports":                                {"azurerm_express_route_port"},
	"network/expressrouteports/authorizations":                 {"azurerm_express_route_port_authorization"},
	"network/firewallpolicies":                                 {"azurerm_firewall_policy"},
	"network/firewallpolicies/rulecollectiongroups":            {"azurerm_firewall_policy_rule_collection_group"},
	"network/frontdoors":                                       {"azurerm_frontdoor"},
	"network/frontdoors/customhttpsconfiguration":              {"azurerm_frontdoor_custom_https_configuration"},
	"network/frontdoors/rulesengines":                          {"azurerm_frontdoor_rules_engine"},
	"network/frontdoorwebapplicationfirewallpolicies": {
		"azurerm_cdn_frontdoor_firewall_policy",
		"azurerm_frontdoor_firewall_policy",
	},
	"network/ipgroups":                                    {"azurerm_ip_group"},
	"network/ipgroups/cidrs":                              {"azurerm_ip_group_cidr"},
	"network/loadbalancers":                               {"azurerm_lb"},
	"network/loadbalancers/backendaddresspools":           {"azurerm_lb_backend_address_pool"},
	"network/loadbalancers/backendaddresspools/addresses": {"azurerm_lb_backend_address_pool_address"},
	"network/loadbalancers/inboundnatpools":               {"azurerm_lb_nat_pool"},
	"network/loadbalancers/inboundnatrules":               {"azurerm_lb_nat_rule"},
	"network/loadbalancers/loadbalancingrules":            {"azurerm_lb_rule"},
	"network/loadbalancers/outboundrules":                 {"azurerm_lb_outbound_rule"},
	"network/loadbalancers/probes":                        {"azurerm_lb_probe"},
	"network/localnetworkgateways":                        {"azurerm_local_network_gateway"},
	"network/natgateways":                                 {"azurerm_nat_gateway"},
	"network/natgateways/publicipaddresses":               {"azurerm_nat_gateway_public_ip_association"},
	"network/natgateways/publicipprefixes":                {"azurerm_nat_gateway_public_ip_prefix_association"},
	"network/networkinterfaces":                           {"azurerm_network_interface"},
	"network/networkinterfaces/ipconfigurations":          {"fake_azurerm_network_interface_ipconfig"},
	"network/networkinterfaces/ipconfigurations/applicationgatewaybackendaddresspools": {"azurerm_network_interface_application_gateway_backend_address_pool_association"},
	"network/networkinterfaces/ipconfigurations/applicationsecuritygroups":             {"azurerm_network_interface_application_security_group_association"},
	"network/networkinterfaces/ipconfigurations/loadbalancerbackendaddresspools":       {"azurerm_network_interface_backend_address_pool_association"},
	"network/networkinterfaces/ipconfigurations/loadbalancerinboundnatrules":           {"azurerm_network_interface_nat_rule_association"},
	"network/networkinterfaces/networksecuritygroups":                                  {"azurerm_network_interface_security_group_association"},
	"network/networkmanagerconnections": {
		"azurerm_network_manager_management_group_connection",
		"azurerm_network_manager_subscription_connection",
	},
	"network/networkmanagers":                                                   {"azurerm_network_manager"},
	"network/networkmanagers/connectivityconfigurations":                        {"azurerm_network_manager_connectivity_configuration"},
	"network/networkmanagers/ipampools":                                         {"azurerm_network_manager_ipam_pool"},
	"network/networkmanagers/ipampools/staticcidrs":                             {"azurerm_network_manager_ipam_pool_static_cidr"},
	"network/networkmanagers/locations/types":                                   {"azurerm_network_manager_deployment"},
	"network/networkmanagers/networkgroups":                                     {"azurerm_network_manager_network_group"},
	"network/networkmanagers/networkgroups/staticmembers":                       {"azurerm_network_manager_static_member"},
	"network/networkmanagers/routingconfigurations":                             {"azurerm_network_manager_routing_configuration"},
	"network/networkmanagers/routingconfigurations/rulecollections":             {"azurerm_network_manager_routing_rule_collection"},
	"network/networkmanagers/routingconfigurations/rulecollections/rules":       {"azurerm_network_manager_routing_rule"},
	"network/networkmanagers/scopeconnections":                                  {"azurerm_network_manager_scope_connection"},
	"network/networkmanagers/securityadminconfigurations":                       {"azurerm_network_manager_security_admin_configuration"},
	"network/networkmanagers/securityadminconfigurations/rulecollections":       {"azurerm_network_manager_admin_rule_collection"},
	"network/networkmanagers/securityadminconfigurations/rulecollections/rules": {"azurerm_network_manager_admin_rule"},
	"network/networkmanagers/verifierworkspaces":                                {"azurerm_network_manager_verifier_workspace"},
	"network/networkmanagers/verifierworkspaces/reachabilityanalysisintents":    {"azurerm_network_manager_verifier_workspace_reachability_analysis_intent"},
	"network/networkprofiles":                                                   {"azurerm_network_profile"},
	"network/networksecuritygroups":                                             {"azurerm_network_security_group"},
	"network/networksecuritygroups/securityrules":                               {"azurerm_network_security_rule"},
	"network/networksecurityperimeters":                                         {"azurerm_network_security_perimeter"},
	"network/networksecurityperimeters/profiles":                                {"azurerm_network_security_perimeter_profile"},
	"network/networksecurityperimeters/profiles/accessrules":                    {"azurerm_network_security_perimeter_access_rule"},
	"network/networksecurityperimeters/resourceassociations":                    {"azurerm_network_security_perimeter_association"},
	"network/networkvirtualappliances":                                          {"azurerm_palo_alto_virtual_network_appliance"},
	"network/networkwatchers":                                                   {"azurerm_network_watcher"},
	"network/networkwatchers/connectionmonitors":                                {"azurerm_network_connection_monitor"},
	"network/networkwatchers/flowlogs":                                          {"azurerm_network_watcher_flow_log"},
	"network/networkwatchers/packetcaptures": {
		"azurerm_virtual_machine_packet_capture",
		"azurerm_virtual_machine_scale_set_packet_capture",
	},
	"network/p2svpngateways":                           {"azurerm_point_to_site_vpn_gateway"},
	"network/privatednszones":                          {"azurerm_private_dns_zone"},
	"network/privatednszones/a":                        {"azurerm_private_dns_a_record"},
	"network/privatednszones/aaaa":                     {"azurerm_private_dns_aaaa_record"},
	"network/privatednszones/cname":                    {"azurerm_private_dns_cname_record"},
	"network/privatednszones/mx":                       {"azurerm_private_dns_mx_record"},
	"network/privatednszones/ptr":                      {"azurerm_private_dns_ptr_record"},
	"network/privatednszones/srv":                      {"azurerm_private_dns_srv_record"},
	"network/privatednszones/txt":                      {"azurerm_private_dns_txt_record"},
	"network/privatednszones/virtualnetworklinks":      {"azurerm_private_dns_zone_virtual_network_link"},
	"network/privateendpoints":                         {"azurerm_private_endpoint"},
	"network/privatelinkservices":                      {"azurerm_private_link_service"},
	"network/publicipaddresses":                        {"azurerm_public_ip"},
	"network/publicipprefixes":                         {"azurerm_public_ip_prefix"},
	"network/routefilters":                             {"azurerm_route_filter"},
	"network/routetables":                              {"azurerm_route_table"},
	"network/routetables/routes":                       {"azurerm_route"},
	"network/securitypartnerproviders":                 {"azurerm_virtual_hub_security_partner_provider"},
	"network/serviceendpointpolicies":                  {"azurerm_subnet_service_endpoint_storage_policy"},
	"network/trafficmanagerprofiles":                   {"azurerm_traffic_manager_profile"},
	"network/trafficmanagerprofiles/azureendpoints":    {"azurerm_traffic_manager_azure_endpoint"},
	"network/trafficmanagerprofiles/externalendpoints": {"azurerm_traffic_manager_external_endpoint"},
	"network/trafficmanagerprofiles/nestedendpoints":   {"azurerm_traffic_manager_nested_endpoint"},
	"network/virtualhubs": {
		"azurerm_route_server",
		"azurerm_virtual_hub",
	},
	"network/virtualhubs/bgpconnections": {
		"azurerm_route_server_bgp_connection",
		"azurerm_virtual_hub_bgp_connection",
	},
	"network/virtualhubs/hubroutetables":                        {"azurerm_virtual_hub_route_table"},
	"network/virtualhubs/hubroutetables/routes":                 {"azurerm_virtual_hub_route_table_route"},
	"network/virtualhubs/hubvirtualnetworkconnections":          {"azurerm_virtual_hub_connection"},
	"network/virtualhubs/ipconfigurations":                      {"azurerm_virtual_hub_ip"},
	"network/virtualhubs/routemaps":                             {"azurerm_route_map"},
	"network/virtualhubs/routingintent":                         {"azurerm_virtual_hub_routing_intent"},
	"network/virtualnetworkgateways":                            {"azurerm_virtual_network_gateway"},
	"network/virtualnetworkgateways/natrules":                   {"azurerm_virtual_network_gateway_nat_rule"},
	"network/virtualnetworks":                                   {"azurerm_virtual_network"},
	"network/virtualnetworks/dnsservers":                        {"azurerm_virtual_network_dns_servers"},
	"network/virtualnetworks/subnets":                           {"azurerm_subnet"},
	"network/virtualnetworks/subnets/natgateways":               {"azurerm_subnet_nat_gateway_association"},
	"network/virtualnetworks/subnets/networksecuritygroups":     {"azurerm_subnet_network_security_group_association"},
	"network/virtualnetworks/subnets/routetables":               {"azurerm_subnet_route_table_association"},
	"network/virtualnetworks/virtualnetworkpeerings":            {"azurerm_virtual_network_peering"},
	"network/virtualwans":                                       {"azurerm_virtual_wan"},
	"network/vpngateways":                                       {"azurerm_vpn_gateway"},
	"network/vpngateways/natrules":                              {"azurerm_vpn_gateway_nat_rule"},
	"network/vpngateways/vpnconnections":                        {"azurerm_vpn_gateway_connection"},
	"network/vpnserverconfigurations":                           {"azurerm_vpn_server_configuration"},
	"network/vpnserverconfigurations/configurationpolicygroups": {"azurerm_vpn_server_configuration_policy_group"},
	"network/vpnsites":                                          {"azurerm_vpn_site"},

	// NetworkFunction
	"networkfunction/azuretrafficcollectors":                   {"azurerm_network_function_azure_traffic_collector"},
	"networkfunction/azuretrafficcollectors/collectorpolicies": {"azurerm_network_function_collector_policy"},

	// NewRelic.Observability
	"newrelic.observability/monitors":          {"azurerm_new_relic_monitor"},
	"newrelic.observability/monitors/tagrules": {"azurerm_new_relic_tag_rule"},

	// Nginx.NginxPlus
	"nginx.nginxplus/nginxdeployments":                {"azurerm_nginx_deployment"},
	"nginx.nginxplus/nginxdeployments/apikeys":        {"azurerm_nginx_api_key"},
	"nginx.nginxplus/nginxdeployments/certificates":   {"azurerm_nginx_certificate"},
	"nginx.nginxplus/nginxdeployments/configurations": {"azurerm_nginx_configuration"},

	// NotificationHubs
	"notificationhubs/namespaces":                                     {"azurerm_notification_hub_namespace"},
	"notificationhubs/namespaces/notificationhubs":                    {"azurerm_notification_hub"},
	"notificationhubs/namespaces/notificationhubs/authorizationrules": {"azurerm_notification_hub_authorization_rule"},

	// OperationalInsights
	"operationalinsights/clusters":               {"azurerm_log_analytics_cluster"},
	"operationalinsights/querypacks":             {"azurerm_log_analytics_query_pack"},
	"operationalinsights/querypacks/queries":     {"azurerm_log_analytics_query_pack_query"},
	"operationalinsights/workspaces":             {"azurerm_log_analytics_workspace"},
	"operationalinsights/workspaces/dataexports": {"azurerm_log_analytics_data_export_rule"},
	"operationalinsights/workspaces/datasources": {
		"azurerm_log_analytics_datasource_windows_event",
		"azurerm_log_analytics_datasource_windows_performance_counter",
	},
	"operationalinsights/workspaces/linkedservices":        {"azurerm_log_analytics_linked_service"},
	"operationalinsights/workspaces/linkedstorageaccounts": {"azurerm_log_analytics_linked_storage_account"},
	"operationalinsights/workspaces/savedsearches":         {"azurerm_log_analytics_saved_search"},
	"operationalinsights/workspaces/storageinsightconfigs": {"azurerm_log_analytics_storage_insights"},
	"operationalinsights/workspaces/tables":                {"azurerm_log_analytics_workspace_table_custom_log"},

	// OperationsManagement
	"operationsmanagement/solutions": {"azurerm_log_analytics_solution"},

	// Oracle.Database
	"oracle.database/autonomousdatabases": {
		"azurerm_oracle_autonomous_database",
		"azurerm_oracle_autonomous_database_clone_from_backup",
		"azurerm_oracle_autonomous_database_clone_from_database",
	},
	"oracle.database/autonomousdatabases/autonomousdatabasebackups": {"azurerm_oracle_autonomous_database_backup"},
	"oracle.database/cloudexadatainfrastructures":                   {"azurerm_oracle_exadata_infrastructure"},
	"oracle.database/cloudvmclusters":                               {"azurerm_oracle_cloud_vm_cluster"},
	"oracle.database/exascaledbstoragevaults":                       {"azurerm_oracle_exascale_database_storage_vault"},
	"oracle.database/resourceanchors":                               {"azurerm_oracle_resource_anchor"},

	// Orbital
	"orbital/contactprofiles":      {"azurerm_orbital_contact_profile"},
	"orbital/spacecrafts":          {"azurerm_orbital_spacecraft"},
	"orbital/spacecrafts/contacts": {"azurerm_orbital_contact"},

	// PaloAltoNetworks.Cloudngfw
	"paloaltonetworks.cloudngfw/firewalls": {
		"azurerm_palo_alto_next_generation_firewall_virtual_hub_local_rulestack",
		"azurerm_palo_alto_next_generation_firewall_virtual_hub_panorama",
		"azurerm_palo_alto_next_generation_firewall_virtual_hub_strata_cloud_manager",
		"azurerm_palo_alto_next_generation_firewall_virtual_network_local_rulestack",
		"azurerm_palo_alto_next_generation_firewall_virtual_network_panorama",
		"azurerm_palo_alto_next_generation_firewall_virtual_network_strata_cloud_manager",
	},
	"paloaltonetworks.cloudngfw/localrulestacks":              {"azurerm_palo_alto_local_rulestack"},
	"paloaltonetworks.cloudngfw/localrulestacks/certificates": {"azurerm_palo_alto_local_rulestack_certificate"},
	"paloaltonetworks.cloudngfw/localrulestacks/fqdnlists":    {"azurerm_palo_alto_local_rulestack_fqdn_list"},
	"paloaltonetworks.cloudngfw/localrulestacks/localrules":   {"azurerm_palo_alto_local_rulestack_rule"},
	"paloaltonetworks.cloudngfw/localrulestacks/prefixlists":  {"azurerm_palo_alto_local_rulestack_prefix_list"},

	// PolicyInsights
	"policyinsights/remediations": {
		"azurerm_management_group_policy_remediation",
		"azurerm_resource_group_policy_remediation",
		"azurerm_resource_policy_remediation",
		"azurerm_subscription_policy_remediation",
	},

	// Portal
	"portal/dashboards":           {"azurerm_portal_dashboard"},
	"portal/tenantconfigurations": {"azurerm_portal_tenant_configuration"},

	// PowerBIDedicated
	"powerbidedicated/capacities": {"azurerm_powerbi_embedded"},

	// Purview
	"purview/accounts": {"azurerm_purview_account"},

	// Qumulo.Storage
	"qumulo.storage/filesystems": {"azurerm_qumulo_file_system"},

	// RecoveryServices
	"recoveryservices/vaults":                                    {"azurerm_recovery_services_vault"},
	"recoveryservices/vaults/backupfabrics/protectioncontainers": {"azurerm_backup_container_storage_account"},
	"recoveryservices/vaults/backupfabrics/protectioncontainers/protecteditems": {
		"azurerm_backup_protected_file_share",
		"azurerm_backup_protected_vm",
	},
	"recoveryservices/vaults/backuppolicies": {
		"azurerm_backup_policy_file_share",
		"azurerm_backup_policy_vm",
		"azurerm_backup_policy_vm_workload",
	},
	"recoveryservices/vaults/backupresourceguardproxies": {"azurerm_recovery_services_vault_resource_guard_association"},
	"recoveryservices/vaults/replicationfabrics": {
		"azurerm_site_recovery_fabric",
		"azurerm_site_recovery_services_vault_hyperv_site",
	},
	"recoveryservices/vaults/replicationfabrics/replicationnetworks/replicationnetworkmappings": {
		"azurerm_site_recovery_hyperv_network_mapping",
		"azurerm_site_recovery_network_mapping",
	},
	"recoveryservices/vaults/replicationfabrics/replicationprotectioncontainers": {"azurerm_site_recovery_protection_container"},
	"recoveryservices/vaults/replicationfabrics/replicationprotectioncontainers/replicationprotecteditems": {
		"azurerm_site_recovery_replicated_vm",
		"azurerm_site_recovery_vmware_replicated_vm",
	},
	"recoveryservices/vaults/replicationfabrics/replicationprotectioncontainers/replicationprotectioncontainermappings": {
		"azurerm_site_recovery_hyperv_replication_policy_association",
		"azurerm_site_recovery_protection_container_mapping",
		"azurerm_site_recovery_vmware_replication_policy_association",
	},
	"recoveryservices/vaults/replicationpolicies": {
		"azurerm_site_recovery_hyperv_replication_policy",
		"azurerm_site_recovery_replication_policy",
		"azurerm_site_recovery_vmware_replication_policy",
	},
	"recoveryservices/vaults/replicationrecoveryplans": {"azurerm_site_recovery_replication_recovery_plan"},

	// RedHatOpenShift
	"redhatopenshift/openshiftclusters": {"azurerm_redhat_openshift_cluster"},

	// Relay
	"relay/namespaces":                                      {"azurerm_relay_namespace"},
	"relay/namespaces/authorizationrules":                   {"azurerm_relay_namespace_authorization_rule"},
	"relay/namespaces/hybridconnections":                    {"azurerm_relay_hybrid_connection"},
	"relay/namespaces/hybridconnections/authorizationrules": {"azurerm_relay_hybrid_connection_authorization_rule"},

	// ResourceConnector
	"resourceconnector/appliances": {"azurerm_arc_resource_bridge_appliance"},

	// Resources
	"resources/deployments": {
		"azurerm_management_group_template_deployment",
		"azurerm_resource_group_template_deployment",
		"azurerm_subscription_template_deployment",
		"azurerm_tenant_template_deployment",
	},
	"resources/deploymentscripts": {
		"azurerm_resource_deployment_script_azure_cli",
		"azurerm_resource_deployment_script_azure_power_shell",
	},
	"resources/subscriptions/resourcegroups": {"azurerm_resource_group"},

	// ScVmm
	"scvmm/availabilitysets":                    {"azurerm_system_center_virtual_machine_manager_availability_set"},
	"scvmm/clouds":                              {"azurerm_system_center_virtual_machine_manager_cloud"},
	"scvmm/virtualmachineinstances":             {"azurerm_system_center_virtual_machine_manager_virtual_machine_instance"},
	"scvmm/virtualmachineinstances/guestagents": {"azurerm_system_center_virtual_machine_manager_virtual_machine_instance_guest_agent"},
	"scvmm/virtualmachinetemplates":             {"azurerm_system_center_virtual_machine_manager_virtual_machine_template"},
	"scvmm/virtualnetworks":                     {"azurerm_system_center_virtual_machine_manager_virtual_network"},
	"scvmm/vmmservers":                          {"azurerm_system_center_virtual_machine_manager_server"},

	// Search
	"search/searchservices":                            {"azurerm_search_service"},
	"search/searchservices/sharedprivatelinkresources": {"azurerm_search_shared_private_link_service"},

	// Security
	"security/advancedthreatprotectionsettings":       {"azurerm_advanced_threat_protection"},
	"security/assessmentmetadata":                     {"azurerm_security_center_assessment_policy"},
	"security/assessments":                            {"azurerm_security_center_assessment"},
	"security/automations":                            {"azurerm_security_center_automation"},
	"security/autoprovisioningsettings":               {"azurerm_security_center_auto_provisioning"},
	"security/defenderforstoragesettings":             {"azurerm_security_center_storage_defender"},
	"security/devicesecuritygroups":                   {"azurerm_iot_security_device_group"},
	"security/iotsecuritysolutions":                   {"azurerm_iot_security_solution"},
	"security/pricings":                               {"azurerm_security_center_subscription_pricing"},
	"security/securitycontacts":                       {"azurerm_security_center_contact"},
	"security/servervulnerabilityassessments":         {"azurerm_security_center_server_vulnerability_assessment_virtual_machine"},
	"security/servervulnerabilityassessmentssettings": {"azurerm_security_center_server_vulnerability_assessments_setting"},
	"security/settings":                               {"azurerm_security_center_setting"},
	"security/workspacesettings":                      {"azurerm_security_center_workspace"},

	// SecurityInsights
	"securityinsights/alertrules": {
		"azurerm_sentinel_alert_rule_fusion",
		"azurerm_sentinel_alert_rule_machine_learning_behavior_analytics",
		"azurerm_sentinel_alert_rule_ms_security_incident",
		"azurerm_sentinel_alert_rule_nrt",
		"azurerm_sentinel_alert_rule_scheduled",
		"azurerm_sentinel_alert_rule_threat_intelligence",
	},
	"securityinsights/automationrules": {"azurerm_sentinel_automation_rule"},
	"securityinsights/dataconnectors": {
		"azurerm_sentinel_data_connector_aws_cloud_trail",
		"azurerm_sentinel_data_connector_aws_s3",
		"azurerm_sentinel_data_connector_azure_active_directory",
		"azurerm_sentinel_data_connector_azure_advanced_threat_protection",
		"azurerm_sentinel_data_connector_azure_security_center",
		"azurerm_sentinel_data_connector_dynamics_365",
		"azurerm_sentinel_data_connector_iot",
		"azurerm_sentinel_data_connector_microsoft_cloud_app_security",
		"azurerm_sentinel_data_connector_microsoft_defender_advanced_threat_protection",
		"azurerm_sentinel_data_connector_microsoft_threat_intelligence",
		"azurerm_sentinel_data_connector_microsoft_threat_protection",
		"azurerm_sentinel_data_connector_office_365",
		"azurerm_sentinel_data_connector_office_365_project",
		"azurerm_sentinel_data_connector_office_atp",
		"azurerm_sentinel_data_connector_office_irm",
		"azurerm_sentinel_data_connector_office_power_bi",
		"azurerm_sentinel_data_connector_threat_intelligence",
		"azurerm_sentinel_data_connector_threat_intelligence_taxii",
	},
	"securityinsights/metadata":         {"azurerm_sentinel_metadata"},
	"securityinsights/onboardingstates": {"azurerm_sentinel_log_analytics_workspace_onboarding"},
	"securityinsights/securitymlanalyticssettings": {
		"azurerm_sentinel_alert_rule_anomaly_built_in",
		"azurerm_sentinel_alert_rule_anomaly_duplicate",
	},
	"securityinsights/threatintelligence/indicators": {"azurerm_sentinel_threat_intelligence_indicator"},
	"securityinsights/watchlists":                    {"azurerm_sentinel_watchlist"},
	"securityinsights/watchlists/watchlistitems":     {"azurerm_sentinel_watchlist_item"},

	// ServiceBus
	"servicebus/namespaces":                            {"azurerm_servicebus_namespace"},
	"servicebus/namespaces/authorizationrules":         {"azurerm_servicebus_namespace_authorization_rule"},
	"servicebus/namespaces/disasterrecoveryconfigs":    {"azurerm_servicebus_namespace_disaster_recovery_config"},
	"servicebus/namespaces/queues":                     {"azurerm_servicebus_queue"},
	"servicebus/namespaces/queues/authorizationrules":  {"azurerm_servicebus_queue_authorization_rule"},
	"servicebus/namespaces/topics":                     {"azurerm_servicebus_topic"},
	"servicebus/namespaces/topics/authorizationrules":  {"azurerm_servicebus_topic_authorization_rule"},
	"servicebus/namespaces/topics/subscriptions":       {"azurerm_servicebus_subscription"},
	"servicebus/namespaces/topics/subscriptions/rules": {"azurerm_servicebus_subscription_rule"},

	// ServiceFabric
	"servicefabric/clusters":        {"azurerm_service_fabric_cluster"},
	"servicefabric/managedclusters": {"azurerm_service_fabric_managed_cluster"},

	// ServiceLinker
	"servicelinker/linkers": {
		"azurerm_app_service_connection",
		"azurerm_function_app_connection",
		"azurerm_spring_cloud_connection",
	},

	// ServiceNetworking
	"servicenetworking/trafficcontrollers":                  {"azurerm_application_load_balancer"},
	"servicenetworking/trafficcontrollers/associations":     {"azurerm_application_load_balancer_subnet_association"},
	"servicenetworking/trafficcontrollers/frontends":        {"azurerm_application_load_balancer_frontend"},
	"servicenetworking/trafficcontrollers/securitypolicies": {"azurerm_application_load_balancer_security_policy"},

	// SignalRService
	"signalrservice/signalr":                            {"azurerm_signalr_service"},
	"signalrservice/signalr/customcertificates":         {"azurerm_signalr_service_custom_certificate"},
	"signalrservice/signalr/customdomains":              {"azurerm_signalr_service_custom_domain"},
	"signalrservice/signalr/sharedprivatelinkresources": {"azurerm_signalr_shared_private_link_resource"},
	"signalrservice/webpubsub": {
		"azurerm_web_pubsub",
		"azurerm_web_pubsub_socketio",
	},
	"signalrservice/webpubsub/customcertificates":         {"azurerm_web_pubsub_custom_certificate"},
	"signalrservice/webpubsub/customdomains":              {"azurerm_web_pubsub_custom_domain"},
	"signalrservice/webpubsub/hubs":                       {"azurerm_web_pubsub_hub"},
	"signalrservice/webpubsub/sharedprivatelinkresources": {"azurerm_web_pubsub_shared_private_link_resource"},

	// Solutions
	"solutions/applicationdefinitions": {"azurerm_managed_application_definition"},
	"solutions/applications":           {"azurerm_managed_application"},

	// Sql
	"sql/locations/instancefailovergroups":          {"azurerm_mssql_managed_instance_failover_group"},
	"sql/managedinstances":                          {"azurerm_mssql_managed_instance"},
	"sql/managedinstances/administrators":           {"azurerm_mssql_managed_instance_active_directory_administrator"},
	"sql/managedinstances/databases":                {"azurerm_mssql_managed_database"},
	"sql/managedinstances/encryptionprotector":      {"azurerm_mssql_managed_instance_transparent_data_encryption"},
	"sql/managedinstances/securityalertpolicies":    {"azurerm_mssql_managed_instance_security_alert_policy"},
	"sql/managedinstances/startstopschedules":       {"azurerm_mssql_managed_instance_start_stop_schedule"},
	"sql/managedinstances/vulnerabilityassessments": {"azurerm_mssql_managed_instance_vulnerability_assessment"},
	"sql/servers":           {"azurerm_mssql_server"},
	"sql/servers/databases": {"azurerm_mssql_database"},
	"sql/servers/databases/extendedauditingsettings":                 {"azurerm_mssql_database_extended_auditing_policy"},
	"sql/servers/databases/vulnerabilityassessments/rules/baselines": {"azurerm_mssql_database_vulnerability_assessment_rule_baseline"},
	"sql/servers/devopsauditingsettings":                             {"azurerm_mssql_server_microsoft_support_auditing_policy"},
	"sql/servers/dnsaliases":                                         {"azurerm_mssql_server_dns_alias"},
	"sql/servers/elasticpools":                                       {"azurerm_mssql_elasticpool"},
	"sql/servers/encryptionprotector":                                {"azurerm_mssql_server_transparent_data_encryption"},
	"sql/servers/extendedauditingsettings":                           {"azurerm_mssql_server_extended_auditing_policy"},
	"sql/servers/failovergroups":                                     {"azurerm_mssql_failover_group"},
	"sql/servers/firewallrules":                                      {"azurerm_mssql_firewall_rule"},
	"sql/servers/jobagents":                                          {"azurerm_mssql_job_agent"},
	"sql/servers/jobagents/credentials":                              {"azurerm_mssql_job_credential"},
	"sql/servers/jobagents/jobs":                                     {"azurerm_mssql_job"},
	"sql/servers/jobagents/jobs/schedules":                           {"azurerm_mssql_job_schedule"},
	"sql/servers/jobagents/jobs/steps":                               {"azurerm_mssql_job_step"},
	"sql/servers/jobagents/targetgroups":                             {"azurerm_mssql_job_target_group"},
	"sql/servers/outboundfirewallrules":                              {"azurerm_mssql_outbound_firewall_rule"},
	"sql/servers/securityalertpolicies":                              {"azurerm_mssql_server_security_alert_policy"},
	"sql/servers/virtualnetworkrules":                                {"azurerm_mssql_virtual_network_rule"},
	"sql/servers/vulnerabilityassessments":                           {"azurerm_mssql_server_vulnerability_assessment"},

	// SqlVirtualMachine
	"sqlvirtualmachine/sqlvirtualmachinegroups":                            {"azurerm_mssql_virtual_machine_group"},
	"sqlvirtualmachine/sqlvirtualmachinegroups/availabilitygrouplisteners": {"azurerm_mssql_virtual_machine_availability_group_listener"},
	"sqlvirtualmachine/sqlvirtualmachines":                                 {"azurerm_mssql_virtual_machine"},

	// StandbyPool
	"standbypool/standbyvirtualmachinepools": {"azurerm_virtual_machine_scale_set_standby_pool"},

	// Storage
	"storage/storageaccounts":                                              {"azurerm_storage_account"},
	"storage/storageaccounts/blobservices/containers":                      {"azurerm_storage_container"},
	"storage/storageaccounts/blobservices/containers/blobs":                {"azurerm_storage_blob"},
	"storage/storageaccounts/blobservices/containers/immutabilitypolicies": {"azurerm_storage_container_immutability_policy"},
	"storage/storageaccounts/dfs":                                          {"azurerm_storage_data_lake_gen2_filesystem"},
	"storage/storageaccounts/dfs/paths":                                    {"azurerm_storage_data_lake_gen2_path"},
	"storage/storageaccounts/encryptionscopes":                             {"azurerm_storage_encryption_scope"},
	"storage/storageaccounts/fileservices/shares":                          {"azurerm_storage_share"},
	"storage/storageaccounts/fileservices/shares/directories":              {"azurerm_storage_share_directory"},
	"storage/storageaccounts/fileservices/shares/files":                    {"azurerm_storage_share_file"},
	"storage/storageaccounts/invetorypolicies":                             {"azurerm_storage_blob_inventory_policy"},
	"storage/storageaccounts/localusers":                                   {"azurerm_storage_account_local_user"},
	"storage/storageaccounts/managementpolicies":                           {"azurerm_storage_management_policy"},
	"storage/storageaccounts/objectreplicationpolicies":                    {"azurerm_storage_object_replication"},
	"storage/storageaccounts/queueservices":                                {"azurerm_storage_account_queue_properties"},
	"storage/storageaccounts/queueservices/queues":                         {"azurerm_storage_queue"},
	"storage/storageaccounts/staticwebsites":                               {"azurerm_storage_account_static_website"},
	"storage/storageaccounts/tableservices/tables":                         {"azurerm_storage_table"},
	"storage/storageaccounts/tableservices/tables/partitionkeys/rowkeys":   {"azurerm_storage_table_entity"},

	// StorageCache
	"storagecache/amlfilesystems":             {"azurerm_managed_lustre_file_system"},
	"storagecache/caches":                     {"azurerm_hpc_cache"},
	"storagecache/caches/cacheaccesspolicies": {"azurerm_hpc_cache_access_policy"},
	"storagecache/caches/storagetargets": {
		"azurerm_hpc_cache_blob_nfs_target",
		"azurerm_hpc_cache_blob_target",
		"azurerm_hpc_cache_nfs_target",
	},

	// StorageMover
	"storagemover/storagemovers":        {"azurerm_storage_mover"},
	"storagemover/storagemovers/agents": {"azurerm_storage_mover_agent"},
	"storagemover/storagemovers/endpoints": {
		"azurerm_storage_mover_source_endpoint",
		"azurerm_storage_mover_target_endpoint",
	},
	"storagemover/storagemovers/projects":                {"azurerm_storage_mover_project"},
	"storagemover/storagemovers/projects/jobdefinitions": {"azurerm_storage_mover_job_definition"},

	// StorageSync
	"storagesync/storagesyncservices":                            {"azurerm_storage_sync"},
	"storagesync/storagesyncservices/syncgroups":                 {"azurerm_storage_sync_group"},
	"storagesync/storagesyncservices/syncgroups/cloudendpoints":  {"azurerm_storage_sync_cloud_endpoint"},
	"storagesync/storagesyncservices/syncgroups/serverendpoints": {"azurerm_storage_sync_server_endpoint"},

	// StreamAnalytics
	"streamanalytics/clusters":                  {"azurerm_stream_analytics_cluster"},
	"streamanalytics/clusters/privateendpoints": {"azurerm_stream_analytics_managed_private_endpoint"},
	"streamanalytics/streamingjobs":             {"azurerm_stream_analytics_job"},
	"streamanalytics/streamingjobs/functions": {
		"azurerm_stream_analytics_function_javascript_uda",
		"azurerm_stream_analytics_function_javascript_udf",
	},
	"streamanalytics/streamingjobs/inputs": {
		"azurerm_stream_analytics_reference_input_blob",
		"azurerm_stream_analytics_reference_input_mssql",
		"azurerm_stream_analytics_stream_input_blob",
		"azurerm_stream_analytics_stream_input_eventhub",
		"azurerm_stream_analytics_stream_input_eventhub_v2",
		"azurerm_stream_analytics_stream_input_iothub",
	},
	"streamanalytics/streamingjobs/outputs": {
		"azurerm_stream_analytics_output_blob",
		"azurerm_stream_analytics_output_cosmosdb",
		"azurerm_stream_analytics_output_eventhub",
		"azurerm_stream_analytics_output_function",
		"azurerm_stream_analytics_output_mssql",
		"azurerm_stream_analytics_output_powerbi",
		"azurerm_stream_analytics_output_servicebus_queue",
		"azurerm_stream_analytics_output_servicebus_topic",
		"azurerm_stream_analytics_output_synapse",
		"azurerm_stream_analytics_output_table",
	},
	"streamanalytics/streamingjobs/schedule":        {"azurerm_stream_analytics_job_schedule"},
	"streamanalytics/streamingjobs/storageaccounts": {"azurerm_stream_analytics_job_storage_account"},

	// Subscription
	"subscription/aliases": {"azurerm_subscription"},

	// Synapse
	"synapse/privatelinkhubs":                     {"azurerm_synapse_private_link_hub"},
	"synapse/workspaces":                          {"azurerm_synapse_workspace"},
	"synapse/workspaces/administrators":           {"azurerm_synapse_workspace_aad_admin"},
	"synapse/workspaces/bigdatapools":             {"azurerm_synapse_spark_pool"},
	"synapse/workspaces/extendedauditingsettings": {"azurerm_synapse_workspace_extended_auditing_policy"},
	"synapse/workspaces/firewallrules":            {"azurerm_synapse_firewall_rule"},
	"synapse/workspaces/integrationruntimes": {
		"azurerm_synapse_integration_runtime_azure",
		"azurerm_synapse_integration_runtime_self_hosted",
	},
	"synapse/workspaces/keys":                                              {"azurerm_synapse_workspace_key"},
	"synapse/workspaces/linkedservices":                                    {"azurerm_synapse_linked_service"},
	"synapse/workspaces/managedvirtualnetworks/managedprivateendpoints":    {"azurerm_synapse_managed_private_endpoint"},
	"synapse/workspaces/roleassignments":                                   {"azurerm_synapse_role_assignment"},
	"synapse/workspaces/securityalertpolicies":                             {"azurerm_synapse_workspace_security_alert_policy"},
	"synapse/workspaces/sqlpools":                                          {"azurerm_synapse_sql_pool"},
	"synapse/workspaces/sqlpools/extendedauditingsettings":                 {"azurerm_synapse_sql_pool_extended_auditing_policy"},
	"synapse/workspaces/sqlpools/securityalertpolicies":                    {"azurerm_synapse_sql_pool_security_alert_policy"},
	"synapse/workspaces/sqlpools/vulnerabilityassessments":                 {"azurerm_synapse_sql_pool_vulnerability_assessment"},
	"synapse/workspaces/sqlpools/vulnerabilityassessments/rules/baselines": {"azurerm_synapse_sql_pool_vulnerability_assessment_baseline"},
	"synapse/workspaces/sqlpools/workloadgroups":                           {"azurerm_synapse_sql_pool_workload_group"},
	"synapse/workspaces/sqlpools/workloadgroups/workloadclassifiers":       {"azurerm_synapse_sql_pool_workload_classifier"},
	"synapse/workspaces/vulnerabilityassessments":                          {"azurerm_synapse_workspace_vulnerability_assessment"},

	// VideoIndexer
	"videoindexer/accounts": {"azurerm_video_indexer_account"},

	// VoiceServices
	"voiceservices/communicationsgateways":           {"azurerm_voice_services_communications_gateway"},
	"voiceservices/communicationsgateways/testlines": {"azurerm_voice_services_communications_gateway_test_line"},

	// Web
	"web/certificates": {
		"azurerm_app_service_certificate",
		"azurerm_app_service_managed_certificate",
	},
	"web/connections":         {"azurerm_api_connection"},
	"web/hostingenvironments": {"azurerm_app_service_environment_v3"},
	"web/serverfarms":         {"azurerm_service_plan"},
	"web/sites": {
		"azurerm_function_app_flex_consumption",
		"azurerm_linux_function_app",
		"azurerm_linux_web_app",
		"azurerm_logic_app_standard",
		"azurerm_windows_function_app",
		"azurerm_windows_web_app",
	},
	"web/sites/functions":        {"azurerm_function_app_function"},
	"web/sites/hostnamebindings": {"azurerm_app_service_custom_hostname_binding"},
	"web/sites/hybridconnectionnamespaces/relays": {
		"azurerm_function_app_hybrid_connection",
		"azurerm_web_app_hybrid_connection",
	},
	"web/sites/networkconfig":      {"azurerm_app_service_virtual_network_swift_connection"},
	"web/sites/publiccertificates": {"azurerm_app_service_public_certificate"},
	"web/sites/slots": {
		"azurerm_linux_function_app_slot",
		"azurerm_linux_web_app_slot",
		"azurerm_windows_function_app_slot",
		"azurerm_windows_web_app_slot",
	},
	"web/sites/slots/hostnamebindings":         {"azurerm_app_service_slot_custom_hostname_binding"},
	"web/sites/slots/networkconfig":            {"azurerm_app_service_slot_virtual_network_swift_connection"},
	"web/sourcecontrols":                       {"azurerm_source_control_token"},
	"web/staticsites":                          {"azurerm_static_web_app"},
	"web/staticsites/customdomains":            {"azurerm_static_web_app_custom_domain"},
	"web/staticsites/userprovidedfunctionapps": {"azurerm_static_web_app_function_app_registration"},

	// Workloads
	"workloads/sapvirtualinstances": {
		"azurerm_workloads_sap_discovery_virtual_instance",
		"azurerm_workloads_sap_single_node_virtual_instance",
		"azurerm_workloads_sap_three_tier_virtual_instance",
	},
}

// getAzurermResourceType returns the azurerm Terraform provider resource type name(s)
// for a given AzureNamingTool resource path and optional property value.
// Returns a comma-separated string of matching resource types, or an empty string if unknown.
func getAzurermResourceType(resource, property string) string {
	key := strings.ToLower(resource)

	// Try property-specific match first.
	if property != "" {
		propKey := key + "|" + strings.ToLower(property)
		if matches, ok := azurermResourceTypeMap[propKey]; ok {
			return strings.Join(matches, ",")
		}
	}

	// Fall back to resource-only match.
	if matches, ok := azurermResourceTypeMap[key]; ok {
		return strings.Join(matches, ",")
	}

	return ""
}
